developer/config/routes.rb
NewApi::Application.routes.draw do
  get "account/index"

  get "api/index"
  get "statistics/per_date"

  devise_for :accounts

  resource :account, :only => [:show, :edit, :update] do

    member do
      get 'statistics'
    end

    resource :websites, :only => [:create, :destroy]
  end

  root :to => "api#index"

end

developer/app/models/account.rb
class Account
  include Mongoid::Document

  field :websites, :type => Array, :default => Array.new
  field :hoccer_compatible, :type => Boolean

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable


  after_create :generate_keys


  private

  def generate_keys
    self.update_attributes( :api_key => UUID.generate(:compact) )

    digestor = Digest::HMAC.new(
      (Time.now.to_i.to_s + email + api_key), Digest::SHA1
    )

    self.update_attributes( :shared_secret => digestor.base64digest )
  end
end

developer/app/models/api_stats.rb
class ApiStats

  include Mongoid::Document

  class << self

    def map_stats
      return <<-EOF
        function() {
          var pad       = function(n) {
            return n<10 ? '0'+n : n
          }

          var timestamp = this.timestamp.getFullYear() +
                          "-" +
                          pad(( this.timestamp.getMonth() + 1 )) +
                          "-" +
                          pad(this.timestamp.getDate()) +
                          "T" +
                          pad(this.timestamp.getHours()) +
                          ":00:00";

          emit(timestamp, 1);
        }
      EOF
    end

    def reduce_stats
      return <<-EOF
        function(k, vals) {
          var sum=0;

          for (var i in vals) {
            sum += vals[i];
          }

          return sum;
        }
      EOF
    end

    def unique_users_for_api_key api_key

      results = collection.map_reduce(
        map_stats,
        reduce_stats,
        :out    => { :inline => 1},
        :raw    => true,
        :query  => {
          "api_key" => api_key,
          "timestamp" => {"$gt" => 24.hours.ago.utc }
        }
      )["results"]

      data_array = results.map do |h|
        [ h["_id"].to_time.to_i*1000, h["value"]]
      end

      [
        :label  => "Transfers per Hour",
        :data   => data_array,
        :color  => "rgb(65, 170, 193)",
        :grid   => { :color => "rgb(40, 40, 40)" }
      ]

    end

  end

end

developer/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_account!

  def show
  end

  def update
    current_account.update_attribute(
      :hoccer_compatible,
      params[:account][:hoccer_compatible]
    )

    render :text => params.to_json
  end

  def statistics

  end
end

developer/app/controllers/api_controller.rb
class ApiController < ApplicationController
  def index
  end
end

developer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource_or_scope)
    "/account"
  end
end

developer/app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_filter :authenticate_account!
  
  def per_date
    respond_to do |format|
      format.js   { render :json => ApiStats.unique_users_for_api_key(current_account.api_key).to_json }
    end
  end
end

developer/app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_filter :authenticate_account!

  def create
    current_account.websites << params[:website]
    current_account.save

    redirect_to account_path
  end

  def destroy
    current_account.websites.delete params[:format]
    current_account.save

    redirect_to account_path
  end
end

developer/app/helpers/account_helper.rb
module AccountHelper
end

developer/app/helpers/api_helper.rb
module ApiHelper
end

developer/app/helpers/application_helper.rb
module ApplicationHelper
end

developer/app/helpers/statistics_helper.rb
module StatisticsHelper
end

developer/app/helpers/websites_helper.rb
module WebsitesHelper
end

developer/app/views/accounts/show.html.erb
<%= content_for(:headline) { "Developer Dashboard" } %>

<div class="column grid_3">
	<div id="sidebar">
		<ul>
      <li><%= link_to 'General', account_path %></a></li>
			<!-- <li>Your Account</li>
			<li>Statistics</li> -->
			<li><a href="https://developer.hoccer.com">Examples</a></li>
			<li><a href="https://developer.hoccer.com/about_api.html">Documentation</a></li>
			<li><a href="https://www.github.com/hoccer">Plattform Libraries</a></li>
			<li><a href="https://developer.hoccer.com/api_overview.html">REST Spec</a></li>
      <li><%= link_to 'Statistics', statistics_account_path %></li>
			<% unless current_account.nil? %>
        <li><%= link_to 'Logout', destroy_account_session_path %></a></li>
			<% end %>

      <!-- <li id="helpdesk">Help Desk</li> -->
	</div>
</div>

<div class="column grid_9">
  <article id="dashboard">
		<h1>Welcome <%= current_account.email %></h1>

		<section class="note">
    You can now start integrating Linccer magic in your Application.
          We suggest to read the
          <a href="https://developer.hoccer.com/about_api.html">General API Documentation</a>
          and build upon one of our plattform libraries at
          <a href="https://github.com/organizations/hoccer">GitHub</a>.
		<br /><br /> We appreciate your feedback at <a href="mailto:support@hoccer.com">support@hoccer.com</a>.
		</section>

		<section id="api_keys">
			<strong>API-Key:</strong> <%= text_field_tag(:api_key, current_account.api_key) %><br />
			<strong>Shared Secret:</strong>	<%= text_field_tag(:shared_secret, current_account.shared_secret) %>
      <p id="hoccer_compatible_widget">
        <strong></strong>
        <%= check_box_tag( :hoccer_compatible, 'true', current_account.hoccer_compatible ) %>
        <span>Hoccer Compatible?</span>
      </p>
      <p>
        Use this keys to authenticate your clients against the server
        (see in the README's of
        <a href="https://github.com/hoccer">the plattform libraries</a>
        or the <a href="https://developer.hoccer.com/about_api.html">REST API Documentation</a>).
      </p>
		</section>

		<section>
			<h3>Javascript</h3>
      <p>In order to use the
        <a href="https://github.com/hoccer/javascript-api">JavaScript API</a>
        on your website you must enter the sites' urls.
      </p>
		  <div id="website_form">
			  <h4>Your Websites:</h4>

			  <ul>
			    <% current_account.websites.each do |site| %>
			    	<li><%= site %> (<%= link_to 'delete',
			    											 account_websites_path(site),
			    											:confirm => "remove #{site}?",
			    											:method => "delete" %>)
			    	</li>
			    <% end %>

			    <li><%= form_tag( account_websites_path ) do %>
			    	<%= text_field_tag(:website) %>
			    	<%= submit_tag("add") %>
			    <% end %></li>
			  <ul>
		  </div>

      <p>
        We only allow requests from the specified urls. It is importent that
        the protocol matches. If you use both 'https' and 'http' you need to
        enter both urls.
      </p>
		</section>

  </article>
</div>

developer/app/views/accounts/statistics.html.erb
<%= content_for(:headline) { "Developer Dashboard" } %>

  <script src="/flot/jquery.flot.js" type="text/javascript" charset="utf-8"></script>
  <script src="/javascripts/graph.js" type="text/javascript" charset="utf-8"></script>

  <script type="text/javascript" charset="utf-8"></script>
  <script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
      HoccerGraph.graphs();
    });
  </script>

<div class="column grid_3">
	<div id="sidebar">
		<ul>
      <li><%= link_to 'General', account_path %></a></li>
			<!-- <li>Your Account</li>
			<li>Statistics</li> -->
			<li><a href="https://developer.hoccer.com">Examples</a></li>
			<li><a href="https://developer.hoccer.com/about_api.html">Documentation</a></li>
			<li><a href="https://www.github.com/hoccer">Plattform Libraries</a></li>
			<li><a href="https://developer.hoccer.com/api_overview.html">REST Spec</a></li>
      <li><%= link_to 'Statistics', statistics_account_path %></li>
			<% unless current_account.nil? %>
        <li><%= link_to 'Logout', destroy_account_session_path %></a></li>
			<% end %>

      <!-- <li id="helpdesk">Help Desk</li> -->
	</div>
</div>

<div class="column grid_9">
  <article id="dashboard">
    <h1>Statistics for <%= current_account.email %></h1>
    <section>
      <div class="graph" data-url="/statistics/per_date.js" style="width: 600px; height: 400px;"></div>
    </section>
  </article>

</div>

developer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>

    <title>Developer | Hoccer</title>
    <meta charset="utf-8" />

    <!-- www.phpied.com/conditional-comments-block-downloads/ -->
    <!--[if IE]><![endif]-->

    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- Place favicon.ico and apple-touch-icon.png in the root of your domain and delete these references -->
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />

    <link rel="stylesheet" href="/css/ui-lightness/jquery-ui-1.8.5.custom.css">
    <link rel="stylesheet" href="/css/developer.css">
    <link rel="stylesheet" href="http://hoccer.com/wp-content/themes/hoccer/css/defaults.css" />
    <link rel="stylesheet" href="http://hoccer.com/wp-content/themes/hoccer/css/style.css" />

    <link rel="stylesheet" href="/css/code_highlight.css">
    <!-- For the less-enabled mobile browsers like Opera Mini -->
    <link rel="stylesheet" media="handheld" href="/css/handheld.css?v=1" />

    <script src="/javascripts/jquery-1.4.4.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="/javascripts/jquery-ui-1.8.5.custom.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="/javascripts/api-keys.js" type="text/javascript" charset="utf-8"></script>

		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>

    <!-- TABS -->
    <script type="text/javascript" charset="utf-8">
        $().ready(function() {
        $("#wiki-tabs").tabs();
      })
    </script>
  </head>

  <!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->

  <!--[if lt IE 7 ]> <body class="ie6"> <![endif]-->
  <!--[if IE 7 ]>    <body class="ie7"> <![endif]-->
  <!--[if IE 8 ]>    <body class="ie8"> <![endif]-->
  <!--[if IE 9 ]>    <body class="ie9"> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->
    <div id="container">
      <header>
        <div class="row">
          <div class="column grid_3">
            <a href="http://hoccer.com"><img src="/images/logo.jpg" alt="logo" /></a>
          </div>
          <nav id="main_navigation" class="column grid_9">
            <ul>
							<li><a href="http://hoccer.com/webapp">Web App</a></li>
              <li><a href="http://hoccer.com/support/">Support</a></li>
              <li><a href="http://developer.hoccer.com/">Developer</a></li>
              <li><a href="http://hoccer.com/blog/">Blog</a></li>
              <li><a href="http://hoccer.com/company/">Company</a></li>
              <li><a href="http://hoccer.com/contact/">Contact</a></li>
              <li><a href="http://www.twitter.com/hoccer"><img src="http://hoccer.com/wp-content/themes/hoccer/images/twitter.png" alt="twitter"/></a></li>
              <li><a href="http://www.facebook.com/hoccer"><img src="http://hoccer.com/wp-content/themes/hoccer/images/facebook.png" alt="facebook"/></a></li>
            </ul>
          </nav>
        </div>
      </header>
      <div class="page">
        <div class="row">
          <div class="column grid_12 page_header page_header_small">
            <h1><%= yield :headline %></h1>
          </div>
        </div>
        <div class="row" id="articles">
            <%= yield %>
        </div>

      </div>
    </div>
    <%= render :partial => 'static/footer' %>
  </body>
</html>

developer/app/views/shared/_index.erb
<div id="gollum-root">h2. Geocialize your software!

p. Add Hoccer-like connectivity to your app in minutes! 

p. Use our open Linccer Connection API to link devices at hand and give your users the ability to simply connect devices, join for a game or to collaborate off the cuff.

h2. Example Code

<div id="wiki-tabs">
* <a href="#wiki-javascript">Javascript</a>
* <a href="#wiki-java">Java</a>
* <a href="#wiki-objc">iOS</a>
* <a href="#wiki-ruby">Ruby</a>
* <a href="#wiki-android">Android</a>
* <a href="#wiki-dotnet">C#/.Net</a>

div(code#javascript). 
<pre><code>var linncer = Linccer({"api_key": "your_api_key", "server": "sandbox" });

window.onload = function() {

  if (!Linccer.autoLocate()) {
    linccer.setEnvironmentCoordinates(longitude, latitude, accuracy);
  }

  linccer.on('received', function(data) {
    // do somthing with the received data
  });

  // receive data from a distribution
  linccer.receive('ont-to-many');

  // distribute data
  linccer.send('one-to-many', {arbitrary : 'json data'});

}</code></pre>

div(code#java). 
<pre><code>Linccer linccer = new Linccer(new ClientDescription("Demo App"));

// publish a gps position (lat, long, accuracy)
linccer.onGpsChanged(23.44, 102.13, 100); 

// safely pass data to an other client here and now
linccer.share("one-to-one", new JSONObject("{ 'demo' : 'arbitrary json' }"));

// safely receive passed data from an other client here and now
JSONObject payload = linccer.receive("one-to-one");</code></pre>

div(code#objc). 
<pre><code>- (void)viewDidLoad {
    linccer = [[HCLinccer alloc] initWithApiKey: @"1234567890" 
                                       secret: @"secret!!!11elf"];
    linccer.delegate = self;
}

- (IBAction)send: (id)sender {
    NSDictionary *payload = [NSDictionary dictionaryWithObject: @"World" 
                                                        forKey: @"Hello"];
    [linccer send: payload withMode: HCTransferModeOneToOne];
}

- (IBAction)receive: (id)sender {
    [linccer receiveWithMode: HCTransferModeOneToOne];
}

#pragme mark -
#pragma mark HCLinccer Delegate Methods
- (void)linccerDidRegister: (HCLinccer *)aLinccer {
    NSLog(@"ready for transfering data");
}

- (void)linccer: (HCLinccer *)aLinccer didSendDataWithInfo: (NSDictionary *)info  {
    NSLog(@"successfully send something %@", info);
}

- (void)linccer: (HCLinccer *)aLinccer didReceiveData: (NSArray *)data {
    NSLog(@"received data: %@", data)
}
</code></pre>

div(code#ruby). 
<pre><code># Create new LinccerClient instance
client = LinccerClient.new

# Update client environment
client.update_environment(
  :gps =&gt; {:longitude =&gt; 12.2, :latitude =&gt; 14.2, :accuracy =&gt; 23.0}
)

# Share data
# The share method expects a mode and an arbitrary ruby hash which will
# be transformed to JSON and used as the payload.
c.share( "one-to-one", :foo =&gt; "bar" )

# Receive data
# The receive method expects a mode parameter and returns a ruby hash
# containing the payload
c.receive( "one-to-one" )</code></pre>

div(code#android). 
<pre><code>AsyncLinccer linccer = 
      new AsyncLinccer(new ClientDescription("Demo Android App"));

// publish a gps position obtained from Android's LocationListener
linccer.onGpsChanged(location);

// publish a wifi data obtained from Android's WifiManager
wifiManager = (WifiManager) pContext.getSystemService(Context.WIFI_SERVICE);
linccer.onWifiScanResults(wifiManager.getScanResults());

// creating and Android event handler to give user feedback
Handler handler = new Handler() {
            @Override
            public void handleMessage(Message msg) {
                  String toast = "transfer failed";
                  if (msg.what == AsyncLinccer.MessageType.SHARED)
                     toastMessage = "sharing faild";
                  else if (msg.what == AsyncLinccer.MessageType.RECEIVED)
                     toastMessage = "received " + (JSONObject) msg.obj;
                  
                  Toast.makeText(this, toastMessage, Toast.LENGTH_LONG).show();
            }
         };

// safely pass data to an other client here and now
linccer.asyncShare("one-to-one", 
                    new JSONObject("{ 'demo' : 'arbitrary json' }"), 
                    handler);

// safely receive passed data from an other client here and now
linccer.asyncReceive("one-to-one", handler);</code></pre>

div(code#dotnet). 
<pre><code>Linccer linccer = new Linccer ();
linccer.Config = new ClientConfig ("C# Demo");

// publish a gps position
linccer.Gps = new LocationInfo { Latitude  = 52.5157, 
                                 Longitude = 13.409, 
                                 Accuracy  = 1000 };
linccer.SubmitEnvironment ();

// pass data to an other client here and now
MyDataClass data = new MyDataClass(...); 
linccer.share("one-to-one", data);

// receive passed data from an other client here and now
MyDataClass receivedData = linccer.receive&lt;MyDataClass&gt;("one-to-one");</code></pre>

</div>



p. Read the <a class="internal present" href="about_api.html">API Documentation</a>.

h2. Getting started

<ol>
<li>Choose README file for your specified API: <a href="https://github.com/hoccer/javascript-api">JavaScript</a>, <a href="https://github.com/hoccer/java-api">Java</a>, <a href="https://github.com/hoccer/ruby-api">Ruby</a>, <a href="https://github.com/hoccer/android-api">Android</a>  or <a href="https://github.com/hoccer/linccer-dotnet">C#/.Net</a> and check the genaral <a class="internal present" href="about_api.html">API Documentation</a>
</li>
	<li>Try the examples</li>
	<li>Sign up for your <a class="signup_link" href="/accounts/sign_up">API Key</a>
</li>
	<li>Implement world shattering Apps</li>
	<li><a href="http://github.com">Get involved to improve the APIs and make suggestions</a></li>
</ol>
<b>Our iOS API is currently under development and will be re-published soon</b>
</div>